CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE TABLE "KeyPairs" (
        "Id" uuid NOT NULL,
        "PushKey" character varying(36) NOT NULL,
        "ViewKey" character varying(36) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_KeyPairs" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_KeyPairs_PushKey" UNIQUE ("PushKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE TABLE "RoutePoints" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PushKey" character varying(36) NOT NULL,
        "X" real NOT NULL,
        "Y" real NOT NULL,
        "Z" real NOT NULL,
        "GlobalX" real NOT NULL,
        "GlobalY" real NOT NULL,
        "GlobalZ" real NOT NULL,
        "MapId" bigint NOT NULL,
        "MapIdStr" character varying(20),
        "TimestampMs" numeric(20,0) NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RoutePoints" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoutePoints_KeyPairs_PushKey" FOREIGN KEY ("PushKey") REFERENCES "KeyPairs" ("PushKey") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_KeyPairs_IsActive" ON "KeyPairs" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_KeyPairs_LastActivityAt" ON "KeyPairs" ("LastActivityAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_KeyPairs_PushKey" ON "KeyPairs" ("PushKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_KeyPairs_ViewKey" ON "KeyPairs" ("ViewKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_RoutePoints_PushKey" ON "RoutePoints" ("PushKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_RoutePoints_ReceivedAt" ON "RoutePoints" ("ReceivedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260107110346_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260114154006_AddGlobalMapId') THEN
    ALTER TABLE "RoutePoints" ADD "GlobalMapId" smallint NOT NULL DEFAULT 60;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260114154006_AddGlobalMapId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260114154006_AddGlobalMapId', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    ALTER TABLE "KeyPairs" ADD "UserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Provider" character varying(50) NOT NULL,
        "ProviderId" character varying(255) NOT NULL,
        "Username" character varying(255) NOT NULL,
        "Email" character varying(255),
        "AvatarUrl" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    CREATE INDEX "IX_KeyPairs_UserId" ON "KeyPairs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    CREATE INDEX "IX_Users_LastLoginAt" ON "Users" ("LastLoginAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    CREATE UNIQUE INDEX "IX_Users_Provider_ProviderId" ON "Users" ("Provider", "ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    ALTER TABLE "KeyPairs" ADD CONSTRAINT "FK_KeyPairs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116184430_AddUserAuthentication') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116184430_AddUserAuthentication', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    CREATE TABLE "LinkedProviders" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Provider" character varying(50) NOT NULL,
        "ProviderId" character varying(255) NOT NULL,
        "ProviderUsername" character varying(255) NOT NULL,
        "ProviderEmail" character varying(255),
        "ProviderAvatarUrl" character varying(500),
        "LinkedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LinkedProviders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LinkedProviders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN

                    INSERT INTO "LinkedProviders" ("Id", "UserId", "Provider", "ProviderId", "ProviderUsername", "ProviderEmail", "ProviderAvatarUrl", "LinkedAt")
                    SELECT 
                        gen_random_uuid(),
                        "Id",
                        "Provider",
                        "ProviderId",
                        "Username",
                        "Email",
                        "AvatarUrl",
                        "CreatedAt"
                    FROM "Users"
                    WHERE "Provider" IS NOT NULL AND "ProviderId" IS NOT NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    ALTER TABLE "Users" RENAME COLUMN "Username" TO "DisplayName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    DROP INDEX "IX_Users_Provider_ProviderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    ALTER TABLE "Users" DROP COLUMN "Provider";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    ALTER TABLE "Users" DROP COLUMN "ProviderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    CREATE UNIQUE INDEX "IX_LinkedProviders_Provider_ProviderId" ON "LinkedProviders" ("Provider", "ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    CREATE INDEX "IX_LinkedProviders_UserId" ON "LinkedProviders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    CREATE UNIQUE INDEX "IX_LinkedProviders_UserId_Provider" ON "LinkedProviders" ("UserId", "Provider");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    CREATE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116220000_AddLinkedProviders') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116220000_AddLinkedProviders', '10.0.0');
    END IF;
END $EF$;
COMMIT;

