CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE TABLE "KeyPairs" (
        "Id" uuid NOT NULL,
        "PushKey" character varying(36) NOT NULL,
        "ViewKey" character varying(36) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_KeyPairs" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_KeyPairs_PushKey" UNIQUE ("PushKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE TABLE "RoutePoints" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PushKey" character varying(36) NOT NULL,
        "X" real NOT NULL,
        "Y" real NOT NULL,
        "Z" real NOT NULL,
        "GlobalX" real NOT NULL,
        "GlobalY" real NOT NULL,
        "GlobalZ" real NOT NULL,
        "MapId" bigint NOT NULL,
        "MapIdStr" character varying(20),
        "TimestampMs" numeric(20,0) NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RoutePoints" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoutePoints_KeyPairs_PushKey" FOREIGN KEY ("PushKey") REFERENCES "KeyPairs" ("PushKey") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_KeyPairs_IsActive" ON "KeyPairs" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_KeyPairs_LastActivityAt" ON "KeyPairs" ("LastActivityAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_KeyPairs_PushKey" ON "KeyPairs" ("PushKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_KeyPairs_ViewKey" ON "KeyPairs" ("ViewKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_RoutePoints_PushKey" ON "RoutePoints" ("PushKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    CREATE INDEX "IX_RoutePoints_ReceivedAt" ON "RoutePoints" ("ReceivedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107110346_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260107110346_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260114154006_AddGlobalMapId') THEN
    ALTER TABLE "RoutePoints" ADD "GlobalMapId" smallint NOT NULL DEFAULT 60;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260114154006_AddGlobalMapId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260114154006_AddGlobalMapId', '10.0.0');
    END IF;
END $EF$;
COMMIT;

