-- =============================================================================
-- Route Tracker - Complete Database Setup Script
-- =============================================================================
-- This script creates the database, user, and all tables needed for Route Tracker.
--
-- IMPORTANT: This script is STANDALONE - no source code or .NET required
--
-- Prerequisites:
--   - PostgreSQL 14+ installed and running
--   - Superuser access (postgres)
--
-- Usage:
--   1. Replace {PASSWORD} with your password
--   2. Run: psql -U postgres -f setup-database.sql
--
-- Or use setup-database.sh which does this automatically.
-- =============================================================================

-- Configuration: replace {PASSWORD} with a secure password
\set db_password '{PASSWORD}'

-- =============================================================================
-- Step 1: Create user
-- =============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'route_tracker') THEN
        CREATE ROLE route_tracker WITH LOGIN PASSWORD '{PASSWORD}';
        RAISE NOTICE 'User route_tracker created successfully';
    ELSE
        ALTER ROLE route_tracker WITH PASSWORD '{PASSWORD}';
        RAISE NOTICE 'User route_tracker already exists, password updated';
    END IF;
END
$$;

-- =============================================================================
-- Step 2: Create database
-- =============================================================================

SELECT 'CREATE DATABASE route_tracker OWNER route_tracker'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'route_tracker')\gexec

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE route_tracker TO route_tracker;

-- =============================================================================
-- Step 3: Connect to database and create tables
-- =============================================================================

\c route_tracker

-- Grant schema permissions
GRANT ALL ON SCHEMA public TO route_tracker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO route_tracker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO route_tracker;

-- -----------------------------------------------------------------------------
-- Table: KeyPairs
-- Stores push/view key pairs for real-time tracking
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "KeyPairs" (
    "Id" uuid NOT NULL,
    "PushKey" character varying(36) NOT NULL,
    "ViewKey" character varying(36) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastActivityAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_KeyPairs" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_KeyPairs_PushKey" UNIQUE ("PushKey")
);

-- Indexes for KeyPairs
CREATE UNIQUE INDEX IF NOT EXISTS "IX_KeyPairs_PushKey" ON "KeyPairs" ("PushKey");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_KeyPairs_ViewKey" ON "KeyPairs" ("ViewKey");
CREATE INDEX IF NOT EXISTS "IX_KeyPairs_IsActive" ON "KeyPairs" ("IsActive");
CREATE INDEX IF NOT EXISTS "IX_KeyPairs_LastActivityAt" ON "KeyPairs" ("LastActivityAt");

-- -----------------------------------------------------------------------------
-- Table: RoutePoints
-- Stores player position data points
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "RoutePoints" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PushKey" character varying(36) NOT NULL,
    "X" real NOT NULL,
    "Y" real NOT NULL,
    "Z" real NOT NULL,
    "GlobalX" real NOT NULL,
    "GlobalY" real NOT NULL,
    "GlobalZ" real NOT NULL,
    "MapId" bigint NOT NULL,
    "MapIdStr" character varying(20),
    "GlobalMapId" smallint NOT NULL DEFAULT 60,
    "TimestampMs" numeric(20,0) NOT NULL,
    "ReceivedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RoutePoints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoutePoints_KeyPairs_PushKey" FOREIGN KEY ("PushKey")
        REFERENCES "KeyPairs" ("PushKey") ON DELETE CASCADE
);

-- Indexes for RoutePoints
CREATE INDEX IF NOT EXISTS "IX_RoutePoints_PushKey" ON "RoutePoints" ("PushKey");
CREATE INDEX IF NOT EXISTS "IX_RoutePoints_ReceivedAt" ON "RoutePoints" ("ReceivedAt");

-- -----------------------------------------------------------------------------
-- Table: __EFMigrationsHistory (EF Core compatibility)
-- Allows EF Core to recognize that migrations are applied
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Mark migrations as applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260107110346_InitialCreate', '10.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260114154006_AddGlobalMapId', '10.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

-- =============================================================================
-- Verification
-- =============================================================================

\echo ''
\echo '==================================================='
\echo '  Database setup completed!'
\echo '==================================================='
\echo ''

SELECT 'Tables created:' AS info;
SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;

\echo ''
\echo 'Connection string: Host=localhost;Port=5432;Database=route_tracker;Username=route_tracker;Password=<your_password>'
\echo ''
