// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteTracker.Data;

#nullable disable

namespace RouteTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122194313_AddIsAdminToUser")]
    partial class AddIsAdminToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteTracker.Models.KeyPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PushKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("PushKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("ViewKey")
                        .IsUnique();

                    b.ToTable("KeyPairs");
                });

            modelBuilder.Entity("RouteTracker.Models.LinkedProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderAvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderUsername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique();

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("LinkedProviders");
                });

            modelBuilder.Entity("RouteTracker.Models.RoutePoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("GlobalMapId")
                        .HasColumnType("smallint");

                    b.Property<float>("GlobalX")
                        .HasColumnType("real");

                    b.Property<float>("GlobalY")
                        .HasColumnType("real");

                    b.Property<float>("GlobalZ")
                        .HasColumnType("real");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<string>("MapIdStr")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PushKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TimestampMs")
                        .HasColumnType("numeric(20,0)");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PushKey");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("RouteTracker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("LastLoginAt");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RouteTracker.Models.KeyPair", b =>
                {
                    b.HasOne("RouteTracker.Models.User", "User")
                        .WithMany("KeyPairs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RouteTracker.Models.LinkedProvider", b =>
                {
                    b.HasOne("RouteTracker.Models.User", "User")
                        .WithMany("LinkedProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RouteTracker.Models.RoutePoint", b =>
                {
                    b.HasOne("RouteTracker.Models.KeyPair", "KeyPair")
                        .WithMany("RoutePoints")
                        .HasForeignKey("PushKey")
                        .HasPrincipalKey("PushKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyPair");
                });

            modelBuilder.Entity("RouteTracker.Models.KeyPair", b =>
                {
                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("RouteTracker.Models.User", b =>
                {
                    b.Navigation("KeyPairs");

                    b.Navigation("LinkedProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
