using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RouteTracker.Migrations
{
    /// <inheritdoc />
    public partial class AddBossKills : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: the table/indexes may already exist in environments
            // where they were created without recording this migration in
            // __EFMigrationsHistory. "IF NOT EXISTS" makes applying safe
            // regardless of schema state (no manual reconciliation needed).
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""BossKills"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""PushKey"" character varying(36) NOT NULL,
    ""FlagId"" bigint NOT NULL,
    ""TimestampMs"" numeric(20,0) NOT NULL,
    ""ReceivedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BossKills"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BossKills_KeyPairs_PushKey"" FOREIGN KEY (""PushKey"") REFERENCES ""KeyPairs"" (""PushKey"") ON DELETE CASCADE
);");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_BossKills_PushKey\" ON \"BossKills\" (\"PushKey\");");

            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_BossKills_PushKey_FlagId\" ON \"BossKills\" (\"PushKey\", \"FlagId\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BossKills");
        }
    }
}
